name: Terraform Drift

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  check_drift:
    runs-on: ubuntu-latest
    name: Check for drift of example terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check for drift
        uses: dflook/terraform-check@v1
        with:
          path: terraform
