name: Terraform Development Deployment

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - "!main"

jobs:
  deploy:
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      release-name: $GITHUB_REF_NAME
